import { useEffect, useMemo, useState } from 'react';
import DashboardLayout from '../../layouts/DashboardLayout.jsx';
import Loader from '../../components/common/Loader/Loader.jsx';
import { useToast } from '../../components/common/Toast/Toast.jsx';
import { useAuth } from '../../context/AuthContext.jsx';
import incidentService from '../../services/incidentService.js';

const EMPTY={title:'',description:'',severity:'Medium',affectedAsset:'',assignedTeam:'',assignedTo:''};
const STATUS=['Open','Investigating','Resolved','Closed'];
const SEVERITY=['Critical','High','Medium','Low'];

function Badge({children,type}){return <span style={{display:'inline-block',padding:'4px 9px',borderRadius:999,fontSize:12,fontWeight:700,background:type==='critical'?'#fee2e2':type==='high'?'#ffedd5':type==='resolved'?'#dcfce7':type==='closed'?'#e5e7eb':'#dbeafe',color:type==='critical'?'#b91c1c':type==='high'?'#c2410c':type==='resolved'?'#166534':type==='closed'?'#374151':'#1d4ed8'}}>{children}</span>}
function severityType(s){return s?.toLowerCase()}

export default function IncidentsPage(){
 const {hasPermission}=useAuth(); const toast=useToast();
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[selected,setSelected]=useState(null),[history,setHistory]=useState([]),[sla,setSla]=useState(null);
 const [form,setForm]=useState(EMPTY),[editing,setEditing]=useState(null),[creating,setCreating]=useState(false),[saving,setSaving]=useState(false),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[severity,setSeverity]=useState('');
 const load=async()=>{setLoading(true);try{const r=await incidentService.getAll();setItems(r.data||[])}catch(e){toast(e.response?.data?.message||'Failed to load incidents','error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!selected)return; Promise.all([incidentService.getHistory(selected.id),incidentService.getSla(selected.id)]).then(([h,s])=>{setHistory(h.data||[]);setSla(s.data)}).catch(()=>{});},[selected]);
 const filtered=useMemo(()=>items.filter(i=>(!search||`${i.incidentId} ${i.title} ${i.assignedTeam||''}`.toLowerCase().includes(search.toLowerCase()))&&(!status||i.status===status)&&(!severity||i.severity===severity)),[items,search,status,severity]);
 const summary={active:items.filter(i=>['Open','Investigating'].includes(i.status)).length,critical:items.filter(i=>i.severity==='Critical'&&['Open','Investigating'].includes(i.status)).length,resolved:items.filter(i=>i.status==='Resolved').length,breached:items.filter(i=>i.slaStatus==='BREACHED').length};
 const save=async()=>{if(!form.title.trim())return toast('Incident title is required','error');setSaving(true);try{if(editing)await incidentService.update(editing.id,form);else await incidentService.create(form);toast(editing?'Incident updated':'Incident created','success');setEditing(null);setCreating(false);setForm(EMPTY);await load()}catch(e){toast(e.response?.data?.message||'Save failed','error')}finally{setSaving(false)}};
 const changeStatus=async(i,next)=>{try{const r=await incidentService.changeStatus(i.id,next);setItems(x=>x.map(a=>a.id===i.id?r.data:a));setSelected(r.data);toast(`Incident moved to ${next}`,'success')}catch(e){toast(e.response?.data?.message||'Invalid workflow transition','error')}};
 const assign=async()=>{if(!selected?.assignedTeam)return toast('Enter a team name','error');try{const r=await incidentService.assign(selected.id,selected.assignedTeam,selected.assignedTo);setItems(x=>x.map(a=>a.id===selected.id?r.data:a));setSelected(r.data);toast('Incident assigned','success')}catch(e){toast(e.response?.data?.message||'Assignment failed','error')}};
 const resolve=async()=>{const notes=window.prompt('Resolution notes (optional):',selected?.resolutionNotes||'');if(notes===null)return;try{const r=await incidentService.resolve(selected.id,notes);setItems(x=>x.map(a=>a.id===selected.id?r.data:a));setSelected(r.data);toast('Incident resolved','success')}catch(e){toast(e.response?.data?.message||'Resolution failed','error')}};
 const remove=async i=>{if(!window.confirm(`Delete ${i.incidentId}?`))return;try{await incidentService.delete(i.id);toast('Incident deleted','success');if(selected?.id===i.id)setSelected(null);load()}catch(e){toast(e.response?.data?.message||'Delete failed','error')}};
 return <DashboardLayout><section className="content-header" style={{marginBottom:20}}><h1>Security Incident Management <span style={{fontSize:13,color:'var(--text-muted)',fontWeight:400}}>Milestone 2</span></h1></section>
 <div className="kpi-grid" style={{marginBottom:20}}>{[['Active incidents',summary.active],['Critical active',summary.critical],['Resolved',summary.resolved],['SLA breached',summary.breached]].map(([l,v])=><div className="kpi-card" key={l}><div className="kpi-card-title">{l}</div><div className="kpi-card-value">{v}</div></div>)}</div>
 <div style={{display:'flex',gap:10,marginBottom:15,flexWrap:'wrap'}}><input placeholder="Search incident..." value={search} onChange={e=>setSearch(e.target.value)} style={{minWidth:250,padding:10}}/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{STATUS.map(x=><option key={x}>{x}</option>)}</select><select value={severity} onChange={e=>setSeverity(e.target.value)}><option value="">All severity</option>{SEVERITY.map(x=><option key={x}>{x}</option>)}</select>{hasPermission('INCIDENT_CREATE')&&<button className="btn-add" onClick={()=>{setEditing(null);setCreating(true);setForm(EMPTY)}}>+ New Incident</button>}</div>
 {loading?<Loader/>:<div style={{overflowX:'auto'}}><table className="data-table" style={{width:'100%'}}><thead><tr><th>ID</th><th>Incident</th><th>Severity</th><th>Status</th><th>Team</th><th>SLA</th><th>Created</th><th>Actions</th></tr></thead><tbody>{filtered.map(i=><tr key={i.id}><td>{i.incidentId}</td><td><b>{i.title}</b><div style={{fontSize:12,color:'var(--text-muted)'}}>{i.affectedAsset||'No asset'}</div></td><td><Badge type={severityType(i.severity)}>{i.severity}</Badge></td><td><Badge type={i.status.toLowerCase()}>{i.status}</Badge></td><td>{i.assignedTeam||'Unassigned'}</td><td><b style={{color:i.slaStatus==='BREACHED'?'#dc2626':i.slaStatus==='AT_RISK'?'#d97706':'#16a34a'}}>{i.slaStatus}</b><div style={{fontSize:11}}>{i.dueAt?new Date(i.dueAt).toLocaleString():'—'}</div></td><td>{i.createdAt?new Date(i.createdAt).toLocaleString():'—'}</td><td style={{display:'flex',gap:6}}><button className="btn-sm" onClick={()=>setSelected(i)}>Inspect</button>{hasPermission('INCIDENT_MANAGE')&&<button className="btn-sm" onClick={()=>{setEditing(i);setForm({...EMPTY,...i})}}>Edit</button>}{hasPermission('INCIDENT_DELETE')&&<button className="btn-sm" onClick={()=>remove(i)}>Delete</button>}</td></tr>)}</tbody></table></div>}
 {(editing||creating)&&<Modal title={editing?'Edit Incident':'Create Incident'} onClose={()=>{setEditing(null);setCreating(false);setForm(EMPTY)}}><div style={{display:'grid',gap:12}}><input placeholder="Title" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea placeholder="Description" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/><select value={form.severity} onChange={e=>setForm({...form,severity:e.target.value})}>{SEVERITY.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Affected asset" value={form.affectedAsset} onChange={e=>setForm({...form,affectedAsset:e.target.value})}/><input placeholder="Assigned team" value={form.assignedTeam} onChange={e=>setForm({...form,assignedTeam:e.target.value})}/><input placeholder="Assigned operator" value={form.assignedTo} onChange={e=>setForm({...form,assignedTo:e.target.value})}/><button className="btn-add" disabled={saving} onClick={save}>{saving?'Saving...':editing?'Update Incident':'Create Incident'}</button></div></Modal>}
 {selected&&<Modal title={`${selected.incidentId} — ${selected.title}`} onClose={()=>setSelected(null)}><div style={{display:'grid',gap:14}}><div>{<Badge type={severityType(selected.severity)}>{selected.severity}</Badge>} &nbsp; <Badge type={selected.status.toLowerCase()}>{selected.status}</Badge>}</div><p>{selected.description||'No description provided.'}</p><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><label>Team<input value={selected.assignedTeam||''} onChange={e=>setSelected({...selected,assignedTeam:e.target.value})}/></label><label>Operator<input value={selected.assignedTo||''} onChange={e=>setSelected({...selected,assignedTo:e.target.value})}/></label></div><button className="btn-sm" onClick={assign} disabled={!hasPermission('INCIDENT_MANAGE')}>Assign / Reassign</button><div style={{padding:12,border:'1px solid var(--border-color)',borderRadius:8}}><b>SLA: {sla?.status||selected.slaStatus}</b><div>Deadline: {sla?.dueAt?new Date(sla.dueAt).toLocaleString():selected.dueAt?new Date(selected.dueAt).toLocaleString():'—'}</div><div>Remaining: {sla?.breached?'BREACHED':`${sla?.remainingMinutes??0} minutes`}</div></div><div><b>Workflow</b><div style={{display:'flex',gap:8,marginTop:8,flexWrap:'wrap'}}>{STATUS.map((s,idx)=><button key={s} className="btn-sm" disabled={!hasPermission('INCIDENT_MANAGE')||STATUS.indexOf(selected.status)>idx} onClick={()=>changeStatus(selected,s)}>{idx+1}. {s}</button>)}</div></div>{hasPermission('INCIDENT_RESOLVE')&&selected.status==='Investigating'&&<button className="btn-add" onClick={resolve}>Resolve Incident</button>}<div><b>Audit / History</b>{history.length===0?<p style={{color:'var(--text-muted)'}}>No history.</p>:history.map(h=><div key={h.id} style={{padding:'8px 0',borderBottom:'1px solid var(--border-color)',fontSize:12}}><b>{h.action}</b> — {h.fromValue||'—'} → {h.toValue||'—'}<div>{h.changedBy} · {new Date(h.changedAt).toLocaleString()}</div></div>)}</div></div></Modal>}
 </DashboardLayout>
}
function Modal({title,onClose,children}){return <div style={{position:'fixed',inset:0,zIndex:2000,background:'rgba(0,0,0,.5)',display:'flex',alignItems:'center',justifyContent:'center',padding:20}}><div style={{background:'var(--bg-card)',width:'min(720px,100%)',maxHeight:'90vh',overflow:'auto',borderRadius:10,padding:22}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:18}}><h2 style={{margin:0}}>{title}</h2><button onClick={onClose}>×</button></div>{children}</div></div>}
