package com.sentinelcore.secureops.service;
import com.sentinelcore.secureops.dto.*; import com.sentinelcore.secureops.model.*; import com.sentinelcore.secureops.repository.*;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.Duration; import java.time.LocalDateTime; import java.util.*;
@Service
public class IncidentService {
 private static final Map<String,Integer> DEFAULT_SLA=Map.of("Critical",1,"High",2,"Medium",24,"Low",72); private static final List<String> STATUSES=List.of("Open","Investigating","Resolved","Closed");
 private final IncidentRepository repo; private final IncidentHistoryRepository history;
 public IncidentService(IncidentRepository repo,IncidentHistoryRepository history){this.repo=repo;this.history=history;}
 @Transactional public Incident createIncident(Incident i,String user){validateSeverity(i.getSeverity());i.setIncidentId(nextId());i.setStatus("Open");i.setCreatedAt(LocalDateTime.now());i.setUpdatedAt(i.getCreatedAt());i.setCreatedBy(user);i.setUpdatedBy(user);configureSla(i);Incident s=repo.save(i);history.save(new IncidentHistory(s.getId(),s.getIncidentId(),user,"CREATED",null,"Open"));return s;}
 @Transactional public Incident updateIncident(Long id,Incident u,String user){Incident i=getIncidentById(id);String os=i.getStatus(),osev=i.getSeverity();i.setTitle(required(u.getTitle(),"Title is required"));i.setDescription(u.getDescription());validateSeverity(u.getSeverity());i.setSeverity(u.getSeverity());i.setAffectedAsset(u.getAffectedAsset());i.setAssignedTeam(u.getAssignedTeam());i.setAssignedTo(u.getAssignedTo());if(u.getStatus()!=null&&!u.getStatus().equals(i.getStatus()))applyStatus(i,u.getStatus(),u.getResolutionNotes());i.setUpdatedAt(LocalDateTime.now());i.setUpdatedBy(user);configureSla(i);Incident s=repo.save(i);if(!os.equals(s.getStatus()))history.save(h(s,user,"STATUS_CHANGED",os,s.getStatus()));if(!osev.equals(s.getSeverity()))history.save(h(s,user,"SEVERITY_CHANGED",osev,s.getSeverity()));return s;}
 @Transactional public Incident changeStatus(Long id,IncidentStatusRequest r,String user){Incident i=getIncidentById(id);String old=i.getStatus();applyStatus(i,r.getStatus(),r.getResolutionNotes());i.setUpdatedAt(LocalDateTime.now());i.setUpdatedBy(user);Incident s=repo.save(i);history.save(h(s,user,"STATUS_CHANGED",old,s.getStatus()));return s;}
 @Transactional public Incident assign(Long id,IncidentAssignmentRequest r,String user){Incident i=getIncidentById(id);String old=(i.getAssignedTeam()==null?"":i.getAssignedTeam())+"/"+(i.getAssignedTo()==null?"":i.getAssignedTo());i.setAssignedTeam(r.getAssignedTeam().trim());i.setAssignedTo(r.getAssignedTo());i.setUpdatedAt(LocalDateTime.now());i.setUpdatedBy(user);Incident s=repo.save(i);history.save(h(s,user,"ASSIGNED",old,s.getAssignedTeam()+"/"+(s.getAssignedTo()==null?"":s.getAssignedTo())));return s;}
 @Transactional public Incident resolve(Long id,String notes,String user){Incident i=getIncidentById(id);String old=i.getStatus();applyStatus(i,"Resolved",notes);i.setUpdatedAt(LocalDateTime.now());i.setUpdatedBy(user);Incident s=repo.save(i);history.save(h(s,user,"RESOLVED",old,"Resolved"));return s;}
 public Incident getIncidentById(Long id){return repo.findById(id).orElseThrow(()->new IllegalArgumentException("Incident not found: "+id));}
 public List<Incident> getAllIncidents(){return repo.findAllByOrderByCreatedAtDesc();}
 @Transactional public void deleteIncident(Long id,String user){Incident i=getIncidentById(id);history.save(h(i,user,"DELETED",i.getStatus(),"DELETED"));repo.delete(i);}
 public List<IncidentHistory> getHistory(Long id){getIncidentById(id);return history.findByIncidentIdOrderByChangedAtDesc(id);}
 public IncidentSlaDTO getSla(Long id){Incident i=getIncidentById(id);if(i.getDueAt()==null)return new IncidentSlaDTO(i.getSlaStatus(),i.getSlaHours(),null,0,false);long r=Duration.between(LocalDateTime.now(),i.getDueAt()).toMinutes();return new IncidentSlaDTO(i.getSlaStatus(),i.getSlaHours(),i.getDueAt(),Math.max(0,r),r<0);}
 public List<StatusCount> getIncidentStatusCounts(){return repo.getIncidentStatusCounts();}
 private void configureSla(Incident i){int hours=i.getSlaHours()!=null&&i.getSlaHours()>0?i.getSlaHours():DEFAULT_SLA.getOrDefault(i.getSeverity(),24);i.setSlaHours(hours);if(i.getCreatedAt()==null)i.setCreatedAt(LocalDateTime.now());if(!"Resolved".equalsIgnoreCase(i.getStatus())&&!"Closed".equalsIgnoreCase(i.getStatus()))i.setDueAt(i.getCreatedAt().plusHours(hours));}
 private void applyStatus(Incident i,String status,String notes){if(status==null||!STATUSES.contains(status))throw new IllegalArgumentException("Invalid incident status. Use Open, Investigating, Resolved or Closed.");int c=STATUSES.indexOf(i.getStatus()),t=STATUSES.indexOf(status);if(t<c)throw new IllegalArgumentException("Incident workflow cannot move backwards from "+i.getStatus()+" to "+status);if("Resolved".equals(status)){i.setResolvedAt(LocalDateTime.now());i.setResolutionNotes(notes);}if("Closed".equals(status)){if(i.getResolvedAt()==null)i.setResolvedAt(LocalDateTime.now());i.setClosedAt(LocalDateTime.now());if(notes!=null&&!notes.isBlank())i.setResolutionNotes(notes);}i.setStatus(status);}
 private void validateSeverity(String s){if(s==null||!DEFAULT_SLA.containsKey(s))throw new IllegalArgumentException("Severity must be Critical, High, Medium or Low");}
 private String nextId(){return "INC-"+(1000+repo.count()+1);} private String required(String v,String m){if(v==null||v.isBlank())throw new IllegalArgumentException(m);return v.trim();} private IncidentHistory h(Incident i,String u,String a,String f,String t){return new IncidentHistory(i.getId(),i.getIncidentId(),u,a,f,t);}
}
